### ISSUE TITLE
setting up ssh from VS code taking longer

### ISSUE THREAD

**Issue by BrahmaFarmsLLC** [jimbobbennett/AgroHack#5]
I am trying to connect to raspeberrypi from VS code and the connectivity is taking too long. 

at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)

**Comment by jimbobbennett** [comment]
Nothing to do with this repo - if you are having issues with the extension, raise them on the VS Code remote repo: https://github.com/Microsoft/vscode-remote-release
